theme: minima
title: Testing out GH Pages
author: David Cash
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I need to figure ou thow ot work this GH pages out for the new website. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: davecash75 # DO NOT include the @ character, or else the build will fail!
github_username:  davecash75 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
